### ISSUE TITLE
[REQUEST] Profiles doesn't work

### ISSUE THREAD

**Issue by Darkman06660** [niketa-wow/farmingbar#21]
**Describe the bug**
Hi, I would like to create a profile with several bars on a character and use the profile with another character but when I select the profile on the second character nothing happend. I have only the default bars.

**Client**
WOW retail 9.0.1.

**Comment by niketa-wow** [comment]
Profiles mostly have visual settings only. Things such as the skins, whether you want to show the include bank overlay, etc.

What are you trying to save across multiple toons? If it's the objectives tracked on your bars, take a look at using templates. If it's something else that you think should be profile based and not character based, let me know.

**Comment by Darkman06660** [comment]
Hi and thank you for your time,

I want to save a bar with 24 buttons for all my toons. I create this bar in the default profile with a toon but i can't see it with the other toons.

**Comment by niketa-wow** [comment]
Is it just the number of buttons per bar that you mean? Or do you mean 24 buttons with the objectives on them?

If it's just buttons I can probably add a default bar size as a profile setting. If you mean with the objectives, you'll have to save it as a template and load them on each toon you want it on.

I can probably look into some sort of template profile setting and I have a rough idea of how I could do it but I won't make any promises until I can think it over more.

**Comment by niketa-wow** [comment]
This will be changed in the v3.0-alpha2.
