### ISSUE TITLE
[REQUEST]  -  Add /FB to open the addon main interface 

### ISSUE THREAD

**Issue by EyeSage** [niketa-wow/farmingbar#25]
Description:  /Farmingbar is longer than it needs to be.   I like short abbreviations. 

Add /FB to open the addon Main Interface.   Don't remove the current was as some people like that too.

**Comment by niketa-wow** [comment]
This feature already exists. You can use: /farmbar /farm /fbar /fb

/fb is disabled by default because Fishing Buddy uses it, but you can enable it in the settings b

**Comment by EyeSage** [comment]
Thankyou

I found it.

FYI - I use TSM and with TSM when I hover over something in the Fbar it
will show me how much I have of something on each character and above the
list by char, it has the inventory total.   So if people get that addon
then you don't need to code that stuff in your program.   It also show how
my ah toon has in the inventory plus what is in the AH.
