### ISSUE TITLE
[BUG] Bars.lua:534: attempt to compare number with nil

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farmingbar#26]
**Describe the bug**
I was in a raid in MC and I was hiding a bar because it was covering the raid icons and this error appeared:

3x FarmingBar\Core\Bars.lua:534: attempt to compare number with nil
[string "@FarmingBar\Core\Bars.lua"]:534: in function <FarmingBar\Core\Bars.lua:533>

Locals:
self = FarmingBarBar4AnchorButtonIDEditBox {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = 100
(*temporary) = nil
(*temporary) = ""
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
addon = <table> {
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 SetObjectiveID = <function> defined @FarmingBar\Core\Buttons.lua:125
 DrawShoppingListGroup = <function> defined @FarmingBar\Modules\ObjectiveBuilder.lua:867
 RemoveBar = <function> defined @FarmingBar\Core\Bars.lua:651
 SetDefaultModulePrototype = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 IsEnabled = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @DataStore\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 minButtonPadding = -3
 maxButtonPadding = 20
 MoveShoppingList = <function> defined @FarmingBar\Modules\ItemMover.lua:226
 SortObjectives = <function> defined @FarmingBar\Modules\ObjectiveBuilder.lua:1096
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DeleteTemplate = <function> defined @FarmingBar\Modules\Templates.lua:90
 ResetProfile = <function> defined @FarmingBar\Core\Bars.lua:683
 db = <table> {
 }
 SetEnabledState = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 GetDirection = <function> defined @FarmingBar\Core\Buttons.lua:101
 barProgress = "%B progress: %progressColor%%c/%t%color%%if(%p>0, (%p%%),)if%"
 OnEnable = <function> defined @FarmingBar\Core\Core.lua:10
 CreateDataObject = <function> defined @FarmingBar\Options\Interface.lua:10
 bagIDs = <table> {
 }
 minFontSize = 4
 MoveItems = <function> defined @FarmingBar\Modules\ItemMover.lua:187
 OnInitialize = <function> defined @FarmingBar\Core\Core.lua:47
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 ParseBarAlert = <function> defined @FarmingBar\Core\Bars.lua:86
 CreateButton = <function> defined @FarmingBar\Core\Buttons.lua:113
 maxFontSize = 32
 directionInfo = <table> {
 }
 UpdateMedia = <function> defined @FarmingBar\Modules\Skin.lua:232
 ConvertDB = <function> defined @FarmingBar\Data\Database.lua:8
 GetName = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 GetOptions = <function> defined @FarmingBar\Options\Interface.lua:2604
 DrawItemGroup = <function> defined @FarmingBar\Modules\ObjectiveBuilder.lua:478
 name = "Farming Bar"
 Disable = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 Print = <function> defined @DataStore\libs\AceConsole-3.0\AceConsole-3.0.lua:54
 ObjectiveBuilder = <table> {
 }
 templates = <table> {
 }
 CreateCoFrame = <function> defined @FarmingBar\Modules\ItemMover.lua:341
 SetMixedDBValues = <function> defined @FarmingBar\Data\Database.lua:173
 configOptions = <table> {
 }
 GetAboutOptions = <function> defined @FarmingBar\Options\Interface.lua:58
 GetMixedDBValues = <function> defined @FarmingBar\Data\Database.lua:112
 SplitItem = <function> defined @FarmingBar\Modules\ItemMover.lua:253
 UnregisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SetDefaultModuleLibraries = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 EnableModule = <function> defined @AngryAssignments\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 baseName = "FarmingBar"
 I

After that, every time I hid a keystroke, the error would repeat.  It was so strange.

**Client**

Classic TBC 2.5.1

**To Reproduce**
1. Shift-right-click on a floating tab of a toolbar.
2. Select 'Hidden'
3. Close interface.

**Expected behavior**
I expected to do the same as above with no errors.

**Screenshots**

**Additional context**
It would be very hard to reproduce since that would mean I would have to join another raid.

**Comment by niketa-wow** [comment]
Was this during an encounter, in an instance, or just in a raid group?

**Comment by niketa-wow** [comment]
Are you using the stable build or alpha?

**Comment by rbpaiett** [comment]
This is a stable build and the toolbar was hidden and I made it visible.

**Comment by niketa-wow** [comment]
Since I don't play classic, I won't be able to test in a raid group. However I will do my best to fix the issue blind and once I do that, an update from you on how it is would be great.

Sorry this is taking a while. I've been very very busy.

**Comment by niketa-wow** [comment]
See [v2.1.6.1](https://github.com/niketa-wow/farmingbar/releases/tag/v2.1.6.1).

Again, I can't test the issues with hiding the bar in the raid, but I fixed the source of the lua error you provided.

**Comment by rbpaiett** [comment]
Thank you very much!
