### ISSUE TITLE
[REQUEST] Ability to set thresholds in Classic/TBCC

### ISSUE THREAD

**Issue by icecloud4** [niketa-wow/farmingbar#27]
**Is your feature request related to a problem? Please describe.**
Technically not a problem, more of a feature request. I would love to be able to set a threshold of an item I am farming on the bar. For example, Heavy Leather. If I know I will need a grand total of 95 to level my leatherworking through the Heavy Leather phase. I would love for Farming Bar to allow me to set a threshold and then pop up or flash my screen to indicate the goal has been reached.

**Describe the solution you'd like**
The solution could be GUI defined or script defined. I'm not sure how you would do it with the GUI (maybe have something where you could right click or ctrl click on a item being farmed and then type in the threshold). For script defined it could be as simple as /fb bar [1,1,95], where the first is the actual bar being called, the second being the "box" on said bar, and the third being the desired threshold.

**Describe alternatives you've considered**
N/A

**Additional context**
The final thing would be the way for Farming Bar to interface and "alert" when you have reached your threshold/goal. Again a flash would be nice or something visual beyond the standard "Heavy Leather x 95". Have no idea how this could be done though.

**Comment by niketa-wow** [comment]
This is already a basic feature in the add-on. 

Ctrl click should bring up a box that you can type an objective into. Then press enter. Alerts are different for tracked objectives.
