### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Addonman** [niketa-wow/farmingbar#28]
retail 

Message: ..\AddOns\FarmingBar\Modules\Tooltips.lua line 84:
   bad argument #1 to 'strsub' (string expected, got nil)
Debug:
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@FarmingBar\Modules\Tooltips.lua"]:84: ?()
   [string "@FarmingBar\Modules\Tooltips.lua"]:50:
      FarmingBar\Modules\Tooltips.lua:42
Locals:
private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:48
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:90
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:110
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:86
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:119
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:80
 NewError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:52
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:97
}
orig_errorhandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717

**Comment by niketa-wow** [comment]
Need to know game version please.

**Comment by niketa-wow** [comment]
I also need more information.

1. What version is this? E.g. v3.0-alpha8?
2. Does the bar work besides the tooltip? E.g. you can add/remove objectives, use keybinds on either the anchor or button.
3. Do other parts of the tooltip show up before it has an error?
3.2. If so, what is the value for Growth Direction?
4. It may be helpful to see your saved variables so I can check for a tainted database.

**Comment by Addonman** [comment]
i usually install alpha build but looking at files version it was  latest relaese since i just installed it last night. It worked for most part, i think it thown erro was i was setting profile. My setup for growth direction was up.
FarmingBarDB = {
	["char"] = {
		["Airdh - Twisting Nether"] = {
			["bars"] = {
				{
					["objectives"] = {
						{
							["trackers"] = {
								["ITEM:171831"] = {
									["order"] = 1,
								},
							},
							["action"] = "ITEM",
							["actionInfo"] = 171831,
							["icon"] = 3537032,
							["title"] = "Phaedrum Ore",
						}, -- [1]
						{
							["trackers"] = {
								["ITEM:171829"] = {
									["order"] = 1,
								},
							},
							["action"] = "ITEM",
							["actionInfo"] = 171829,
							["icon"] = 3731242,
							["title"] = "Solenium Ore",
						}, -- [2]
						{
							["trackers"] = {
								["ITEM:171840"] = {
									["order"] = 1,
								},
							},
							["action"] = "ITEM",
							["actionInfo"] = 171840,
							["icon"] = 3764219,
							["title"] = "Porous Stone",
						}, -- [3]
						{
							["trackers"] = {
								["ITEM:171828"] = {
									["order"] = 1,
								},
							},
							["action"] = "ITEM",
							["actionInfo"] = 171828,
							["icon"] = 3594132,
							["title"] = "Laestrite Ore",
						}, -- [4]
						{
							["trackers"] = {
								["ITEM:170554"] = {
									["order"] = 1,
								},
							},
							["action"] = "ITEM",
							["actionInfo"] = 170554,
							["icon"] = 3387974,
							["title"] = "Vigil's Torch",
						}, -- [5]
						{
							["trackers"] = {
								["ITEM:168586"] = {
									["order"] = 1,
								},
							},
							["title"] = "Rising Glory",
							["actionInfo"] = 168586,
							["icon"] = 3613630,
							["action"] = "ITEM",
						}, -- [6]
						{
							["trackers"] = {
								["ITEM:169701"] = {
									["order"] = 1,
								},
							},
							["title"] = "Death Blossom",
							["actionInfo"] = 169701,
							["icon"] = 3502461,
							["action"] = "ITEM",
						}, -- [7]
						{
							["trackers"] = {
								["ITEM:168589"] = {
									["order"] = 1,
								},
							},
							["title"] = "Marrowroot",
							["actionInfo"] = 168589,
							["icon"] = 3480675,
							["action"] = "ITEM",
						}, -- [8]
					},
				}, -- [1]
			},
		},
	},
	["global"] = {
		["version"] = 4,
	},
	["profileKeys"] = {
		["Airlock - Xavius"] = "Airlock - Xavius",
		["Airmago - Twisting Nether"] = "Airmago - Twisting Nether",
		["Airsham - Twisting Nether"] = "Airsham - Twisting Nether",
		["Airofcro - Twisting Nether"] = "Airofcro - Twisting Nether",
		["Airmonk - Silvermoon"] = "Airmonk - Silvermoon",
		["Airkiller - Twisting Nether"] = "Airkiller - Twisting Nether",
		["Airsham - Xavius"] = "Airsham - Xavius",
		["Airpala - Xavius"] = "Airpala - Xavius",
		["Airkiller - Xavius"] = "Airkiller - Xavius",
		["Airdh - Silvermoon"] = "Airdh - Silvermoon",
		["Airmage - Xavius"] = "Airmage - Xavius",
		["Airbear - Twisting Nether"] = "Airbear - Twisting Nether",
		["Airdh - Twisting Nether"] = "AIR",
		["Airhunt - Xavius"] = "Airhunt - Xavius",
		["Airlocko - Twisting Nether"] = "Airlocko - Twisting Nether",
		["Guesswhois - Xavius"] = "Guesswhois - Xavius",
		["Airdoc - Xavius"] = "Airdoc - Xavius",
		["Airdk - Twisting Nether"] = "Airdk - Twisting Nether",
		["Airhunt - Twisting Nether"] = "AIR",
		["Airdruid - Xavius"] = "Airdruid - Xavius",
		["Airmonk - Twisting Nether"] = "AIR",
		["Airpala - Twisting Nether"] = "Airpala - Twisting Nether",
		["Airdoc - Twisting Nether"] = "Airdoc - Twisting Nether",
		["Airofcro - Xavius"] = "Airofcro - Xavius",
	},
	["profiles"] = {
		["Airlock - Xavius"] = {
			["bars"] = {
				{
					["point"] = {
						nil, -- [1]
						nil, -- [2]
						"TOP", -- [3]
						5.999979019165039, -- [4]
						-37.99995803833008, -- [5]
					},
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airmago - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airsham - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airofcro - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airmonk - Silvermoon"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airkiller - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airkiller - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["AIR"] = {
			["bars"] = {
				{
					["grow"] = {
						"UP", -- [1]
					},
					["enabled"] = true,
					["point"] = {
						"BOTTOMRIGHT", -- [1]
						nil, -- [2]
						"BOTTOMRIGHT", -- [3]
						-364.2489318847656, -- [4]
						70.5000991821289, -- [5]
					},
					["numVisibleButtons"] = 8,
				}, -- [1]
			},
		},
		["Airpala - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airsham - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airdh - Silvermoon"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airmage - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airbear - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airdh - Twisting Nether"] = {
			["bars"] = {
				{
					["grow"] = {
						"UP", -- [1]
					},
					["enabled"] = true,
					["point"] = {
						"BOTTOMRIGHT", -- [1]
						nil, -- [2]
						"BOTTOMRIGHT", -- [3]
						-364.2489318847656, -- [4]
						70.5000991821289, -- [5]
					},
					["numVisibleButtons"] = 5,
				}, -- [1]
			},
		},
		["Guesswhois - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airlocko - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airhunt - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
					["point"] = {
						"CENTER", -- [1]
						nil, -- [2]
						"CENTER", -- [3]
						11.99989223480225, -- [4]
						46.25004959106445, -- [5]
					},
					["movable"] = false,
				}, -- [1]
			},
		},
		["Airdk - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airpala - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airmonk - Twisting Nether"] = {
			["bars"] = {
				{
					["point"] = {
						"CENTER", -- [1]
						nil, -- [2]
						"CENTER", -- [3]
						-49.99991226196289, -- [4]
						106.2499771118164, -- [5]
					},
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airdruid - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airdoc - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airhunt - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airdoc - Twisting Nether"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
		["Airofcro - Xavius"] = {
			["bars"] = {
				{
					["enabled"] = true,
				}, -- [1]
			},
		},
	},
}

**Comment by niketa-wow** [comment]
So based on the DB, it looks like it is an alpha build.

After a reload, does the error continue to appear?
Is the error preventing any functionality?
Can you try the latest alpha release and let me know if the error persists?

**Comment by Addonman** [comment]
Nope,havent seen error after latest update alpha.
