### ISSUE TITLE
[BUG] 3.0-alpha7 to 3.0-alpha9 upgrade path unknown event + tooltips error

### ISSUE THREAD

**Issue by Road-block** [niketa-wow/farmingbar#29]
**Describe the bug**
Lua error on login

**Client**
2.5.1 enUS

**To Reproduce**
Login after upgrading from 3.0-alpha (latest that was packaged for 1.13.x before this last round of dev) to 3.0-alpha.9

**Expected behavior**

**Screenshots**
```
1x FarmingBar\Modules\DragFrame.lua:76: Attempt to register unknown event "GLOBAL_MOUSE_DOWN"
[string "=[C]:"]: in function 'RegisterEvent'
[string "@FarmingBar\Modules\DragFrame.lua"]:76: in function 'InitializeDragFrame'
[string "@FarmingBar\Core.lua"]:73: in function <FarmingBar\Core.lua:70>
[string "=[C]:"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function 'EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```
and 
```
37x FarmingBar\Modules\Tooltips.lua:51: attempt to call method 'GetObjective' (a nil value)
[string "@FarmingBar\Modules\Tooltips.lua"]:51: in function <FarmingBar\Modules\Tooltips.lua:47>
```
**Additional context**
Will try to clear saved variables and post a followup comment.
For the moment this is a backup of the saved variables for the previous alpha that worked without errors (last that was packaged for 1.13.x that I was using in BCC)

Note: I did **not** update from 3.x-alpha line to 2.16.x and back to 3.0-alpha9,   
I skipped the stable version entirely and went 3.alpha.7 to 3.alpha.9 directly

3.0-alpha.7 backup saved variables before running 3.0-alpha.9
[FarmingBar-SV.zip](https://github.com/niketa-wow/farmingbar/files/6837076/FarmingBar-SV.zip)

**Comment by Road-block** [comment]
Nuking saved variables `/run FarmingBarDB=nil;ReloadUI()` doesn't change anything with regards to above errors.

**Comment by niketa-wow** [comment]
Did you install v3.0-alpha9-bcc? Or v3.0-alpha9? If it's the latter, then the issue is that you installed the retail version and the resulting error is from something that should only apply to retail builds. I was also unable to replicate the issue with v3.0-alpha9-bcc.

Did you manually install the build or did you use an addon manager to update?

**Comment by niketa-wow** [comment]
To clarify, the error you're getting is happening in a line that should be commented out when packaged for BCC.

**Comment by Road-block** [comment]
> To clarify, the error you're getting is happening in a line that should be commented out when packaged for BCC.

It's likely I messed up and ended up with a git pull in my AddOns folder, I'll check again, but you're most likely correct, feel free to close 😊

**Comment by Road-block** [comment]
Yeah false alarm, apologies.  
I get no errors after I made sure to get proper package, apparently I had the dev branch checked out directly.  

My objectives and trackers didn't migrate from 3.0-alpha.7 but that's expected with alphas.

**Comment by niketa-wow** [comment]
Thanks for the thorough information. Definitely makes things quicker to troubleshoot.

**Comment by niketa-wow** [comment]
> Yeah false alarm, apologies.
> I get no errors after I made sure to get proper package, apparently I had the dev branch checked out directly.
> 
> My objectives and trackers didn't migrate from 3.0-alpha.7 but that's expected with alphas.

I have to apologize, I was picking up development from way back in February and I didn't remember exactly if I cleared the DB or not, but I know there was a DB restructure. I gotta learn to get better at commenting. I started school in the Spring and it's been hard finding time to work on it.

**Comment by Road-block** [comment]
Do you want other issues I find? (with the proper alpha package now 😋 )

Custom condition method seems to have gone missing
```lua
1x ...rface\FarmingBar\Options\ObjectiveBuilder.lua:168: attempt to call method 'ValidateCustomCondition' (a nil value)
[string "@FarmingBar\Options\ObjectiveBuilder.lua"]:168: in function <...rface\FarmingBar\Options\ObjectiveBuilder.lua:166>
[string "=[C]:"]: ?
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua"]:747: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:668>
[string "=[C]:"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function 'Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-MultiLineEditBox.lua"]:61: in function <...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:58>
```

I should make a separate ticket probably
