### ISSUE TITLE
[BUG] [alpha] performance issues

### ISSUE THREAD

**Issue by Road-block** [niketa-wow/farmingbar#33]
**Describe the bug**
There are no Lua errors, I noticed my game "stuttering" (this happens typically when the Lua garbage collector fires) when entering combat constantly to the point of panning the camera around in combat looks like a slideshow 😊.  
Since I keep a log of what addons I update, I started by disabling recently updated addons and testing, when that yielded me no results, I did a binary search (disable half and test, when you find the half that causes the issue, disable half of those and keep narrowing it down)  
Eventually I isolated it to FarmingBar **v3.0-alpha12-bcc** (issue wasn't present in previous alpha)  
I then re-enabled all my other addons __except__ FarmingBar and the issue goes away.

**Client**
2.5.1.39475 (current live BCC) enUS

**Additional context**
[FarmingBar-SavedVariables.zip](https://github.com/niketa-wow/farmingbar/files/6896430/FarmingBar-SavedVariables.zip)

**Comment by niketa-wow** [comment]
Can you clarify, does this persist throughout combat or just when you enter combat? How long does this last?

**Comment by niketa-wow** [comment]
Also if you can do an event trace for me that includes when it starts and stops, that would be helpful.

**Comment by Road-block** [comment]
upon entering combat and during combat, stops when combat stops

**Comment by niketa-wow** [comment]
Widgets/FarmingBar_Button.lua in the block 211 (if trackerCounts...) can you comment out the block or insert an if true then return end to see if it's this causing it? 

My hunch is that it's checking counts too frequently since I added the tracker alerts. Not sure what else I changed that would do this.

**Comment by Road-block** [comment]
Will do when I get a chance (in a run atm)

**Comment by Road-block** [comment]
No change when commenting out that block.

**Comment by niketa-wow** [comment]
Which character? Or is it all? I wanna see if there's any specific traits about the objectives that are causing an issue.

**Comment by Road-block** [comment]
`Bushido`

**Comment by niketa-wow** [comment]
I removed the BAG_UPDATE_COOLDOWN event. BAG_UPDATE should catch all additions, so I believe this event is overkill.

**Comment by Road-block** [comment]
`BAG_UPDATE_DELAYED` that batches bag updates might be an idea then.

**Comment by Road-block** [comment]
I tested alpha13 with switching to the batch bag update event, and issue seems to be gone, at least in solo combat, hoping to test in dungeons next.
