### ISSUE TITLE
[BUG] v3.0-alpha16-bcc fresh install

### ISSUE THREAD

**Issue by Road-block** [niketa-wow/farmingbar#36]
**Describe the bug**
```
1x Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CURSOR_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@FarmingBar\Modules\Bars.lua"]:39: in function `InitializeBars'
[string "@FarmingBar\Core.lua"]:87: in function <FarmingBar\Core.lua:83>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```
followed by
```
12x FarmingBar\Modules\Trackers.lua:137: 'end' expected (to close 'function' at line 132) near 'return'


Locals:
```
and
```
12x FarmingBar\Modules\Templates.lua:228: '}' expected (to close '{' at line 203) near '{'


Locals:

```

**Client**
2.5.3 build 41812

**To Reproduce**
1. Exit the game
2. Search WTF for FarmigBar.*
3. Delete found saved variables.
4. Start the game

**Comment by Road-block** [comment]
Can verify that the BCC client has no `CURSOR_CHANGED` event.

Repro: `/run (CreateFrame"Frame"):RegisterEvent"CURSOR_CHANGED"` in-game

**Comment by Road-block** [comment]
Commenting out the CURSOR_CHANGED event registration reveals another event registered that does not exist on BCC client.

```
1x FarmingBar\Modules\DragFrame.lua:86: Attempt to register unknown event "GLOBAL_MOUSE_DOWN"
[string "=[C]"]: in function `RegisterEvent'
[string "@FarmingBar\Modules\DragFrame.lua"]:86: in function `InitializeDragFrame'
[string "@FarmingBar\Core.lua"]:90: in function <FarmingBar\Core.lua:83>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>
```

**Comment by Road-block** [comment]
Hmm... I can see packager directives at least around the second event registration but it has not been excluded.

**Comment by Road-block** [comment]
The other 2 errors are also blocks that failed to be commented out / excluded by the packager inside -- @retail@ -- @end-retail@ blocks.

**Comment by niketa-wow** [comment]
[Fixed](https://github.com/niketa-wow/farmingbar/releases/tag/v3.0-alpha17)

CURSOR_CHANGED was changed to CURSOR_UPDATE to be valid for retail and TBCC.
Packager tags have been corrected; auto formatter in VSCode added spaces after the comments, when there should be no space in the keywords.
Further bugs with table nesting were also fixed from the non-retail tags.
